name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo ${{ inputs.environment }}
      run: |
        echo ${{ inputs.environment }}
